version: '3.8'
 
networks:
 default:
   external: false
   name: carboncerts-postgres
 
services:
 carboncerts-postgres:
   image: "postgres:13-alpine"
   command: postgres -c 'max_connections=1000'
   restart: always
   container_name: carboncerts-postgres-local
   environment:
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_USER=${DB_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
   volumes:
     - /var/lib/postgresql/data
   ports:
     - "5432:5432"